auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: zihaolucky.com
url: http://zihaolucky.github.io
feed: /atom.xml
author_info: <a href="http://zihaolucky.github.io/">zihaolucky</a>
