auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: ishanshan'blog
url: http://ishanshan.top
feed: /atom.xml
author_info: <a href="http://ishanshan.top/">ishanshan</a>
